Fix image preview for wezterm; still janky though

diff --git a/dot_config/zshrc/dot_zshrc b/dot_config/zshrc/dot_zshrc
--- a/dot_config/zshrc/dot_zshrc
+++ b/dot_config/zshrc/dot_zshrc
@@ -357,6 +357,29 @@ export AIDER_SUBTREE_ONLY=1
 
 . "$HOME/.local/bin/env"
 
+# ----------------------------- Attempt to get terminfo for xterm-kitty
+# -- ( this is needed for wezterm to render kitty images properly in tmux)
+  if ! infocmp xterm-kitty &>/dev/null; then
+    echo "xterm-kitty terminfo not found. Installing..."
+    # Create a temp file
+    tempfile=$(mktemp)
+    # Download the kitty.terminfo file
+    # https://github.com/kovidgoyal/kitty/blob/master/terminfo/kitty.terminfo
+    if curl -o "$tempfile" https://raw.githubusercontent.com/kovidgoyal/kitty/master/terminfo/kitty.terminfo; then
+      echo "Downloaded kitty.terminfo successfully."
+      # Compile and install the terminfo entry for my current user
+      if tic -x -o ~/.terminfo "$tempfile"; then
+        echo "xterm-kitty terminfo installed successfully."
+      else
+        echo "Failed to compile and install xterm-kitty terminfo."
+      fi
+    else
+      echo "Failed to download kitty.terminfo."
+    fi
+    # Remove the temporary file
+    rm "$tempfile"
+  fi
+
 # -----------------------------  rbw (Rust Bitwarden CLI)
 # INFO: native bitwarden cli is too slow w/o session persistence
 # this is a faster alternative that runs as a background daemon;
